# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/Sinead/app/startupdlg.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(575, 700)
        Dialog.setMinimumSize(QtCore.QSize(575, 700))
        Dialog.setMaximumSize(QtCore.QSize(575, 700))
        self.layoutWidget = QtGui.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 20, 531, 661))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.tabWidget = QtGui.QTabWidget(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(516, 250))
        self.tabWidget.setMaximumSize(QtCore.QSize(700, 200))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.analysis = QtGui.QWidget()
        self.analysis.setToolTip(_fromUtf8(""))
        self.analysis.setStyleSheet(_fromUtf8(""))
        self.analysis.setObjectName(_fromUtf8("analysis"))
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.analysis)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 527, 191))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.tissues = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.tissues.setMinimumSize(QtCore.QSize(420, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.tissues.setFont(font)
        self.tissues.setObjectName(_fromUtf8("tissues"))
        self.verticalLayout_2.addWidget(self.tissues)
        self.parenchyma = QtGui.QCheckBox(self.verticalLayoutWidget_2)
        self.parenchyma.setMinimumSize(QtCore.QSize(420, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.parenchyma.setFont(font)
        self.parenchyma.setChecked(True)
        self.parenchyma.setObjectName(_fromUtf8("parenchyma"))
        self.verticalLayout_2.addWidget(self.parenchyma)
        self.haematoma = QtGui.QCheckBox(self.verticalLayoutWidget_2)
        self.haematoma.setMinimumSize(QtCore.QSize(420, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.haematoma.setFont(font)
        self.haematoma.setChecked(True)
        self.haematoma.setObjectName(_fromUtf8("haematoma"))
        self.verticalLayout_2.addWidget(self.haematoma)
        self.ventricles = QtGui.QCheckBox(self.verticalLayoutWidget_2)
        self.ventricles.setMinimumSize(QtCore.QSize(420, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.ventricles.setFont(font)
        self.ventricles.setChecked(True)
        self.ventricles.setObjectName(_fromUtf8("ventricles"))
        self.verticalLayout_2.addWidget(self.ventricles)
        self.wholeBrain = QtGui.QCheckBox(self.verticalLayoutWidget_2)
        self.wholeBrain.setMinimumSize(QtCore.QSize(420, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.wholeBrain.setFont(font)
        self.wholeBrain.setChecked(True)
        self.wholeBrain.setObjectName(_fromUtf8("wholeBrain"))
        self.verticalLayout_2.addWidget(self.wholeBrain)
        self.line = QtGui.QFrame(self.verticalLayoutWidget_2)
        self.line.setMinimumSize(QtCore.QSize(516, 0))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_2.addWidget(self.line)
        self.actions = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.actions.setMinimumSize(QtCore.QSize(420, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Helvetica"))
        font.setPointSize(14)
        self.actions.setFont(font)
        self.actions.setObjectName(_fromUtf8("actions"))
        self.verticalLayout_2.addWidget(self.actions)
        self.symmetry = QtGui.QCheckBox(self.verticalLayoutWidget_2)
        self.symmetry.setMinimumSize(QtCore.QSize(420, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.symmetry.setFont(font)
        self.symmetry.setChecked(True)
        self.symmetry.setObjectName(_fromUtf8("symmetry"))
        self.verticalLayout_2.addWidget(self.symmetry)
        self.segmentation = QtGui.QCheckBox(self.verticalLayoutWidget_2)
        self.segmentation.setMinimumSize(QtCore.QSize(420, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.segmentation.setFont(font)
        self.segmentation.setObjectName(_fromUtf8("segmentation"))
        self.verticalLayout_2.addWidget(self.segmentation)
        spacerItem = QtGui.QSpacerItem(420, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.tabWidget.addTab(self.analysis, _fromUtf8(""))
        self.outputs = QtGui.QWidget()
        self.outputs.setObjectName(_fromUtf8("outputs"))
        self.verticalLayoutWidget_3 = QtGui.QWidget(self.outputs)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 10, 531, 181))
        self.verticalLayoutWidget_3.setObjectName(_fromUtf8("verticalLayoutWidget_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setSizeConstraint(QtGui.QLayout.SetMinAndMaxSize)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.label.setMinimumSize(QtCore.QSize(420, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Helvetica"))
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_3.addWidget(self.label)
        self.totalSymmVolumes = QtGui.QCheckBox(self.verticalLayoutWidget_3)
        self.totalSymmVolumes.setMinimumSize(QtCore.QSize(420, 0))
        self.totalSymmVolumes.setChecked(True)
        self.totalSymmVolumes.setObjectName(_fromUtf8("totalSymmVolumes"))
        self.verticalLayout_3.addWidget(self.totalSymmVolumes)
        self.totalVolumes = QtGui.QCheckBox(self.verticalLayoutWidget_3)
        self.totalVolumes.setMinimumSize(QtCore.QSize(420, 0))
        self.totalVolumes.setChecked(True)
        self.totalVolumes.setObjectName(_fromUtf8("totalVolumes"))
        self.verticalLayout_3.addWidget(self.totalVolumes)
        self.line_2 = QtGui.QFrame(self.verticalLayoutWidget_3)
        self.line_2.setMinimumSize(QtCore.QSize(516, 0))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout_3.addWidget(self.line_2)
        self.label_2 = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.label_2.setMinimumSize(QtCore.QSize(420, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Helvetica"))
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_3.addWidget(self.label_2)
        self.tissueMasks = QtGui.QCheckBox(self.verticalLayoutWidget_3)
        self.tissueMasks.setMinimumSize(QtCore.QSize(420, 0))
        self.tissueMasks.setChecked(True)
        self.tissueMasks.setObjectName(_fromUtf8("tissueMasks"))
        self.verticalLayout_3.addWidget(self.tissueMasks)
        self.lrTissueMasks = QtGui.QCheckBox(self.verticalLayoutWidget_3)
        self.lrTissueMasks.setEnabled(True)
        self.lrTissueMasks.setMinimumSize(QtCore.QSize(420, 0))
        self.lrTissueMasks.setMaximumSize(QtCore.QSize(370, 16777215))
        self.lrTissueMasks.setFocusPolicy(QtCore.Qt.TabFocus)
        self.lrTissueMasks.setCheckable(True)
        self.lrTissueMasks.setChecked(True)
        self.lrTissueMasks.setObjectName(_fromUtf8("lrTissueMasks"))
        self.verticalLayout_3.addWidget(self.lrTissueMasks)
        self.midplaneMask = QtGui.QCheckBox(self.verticalLayoutWidget_3)
        self.midplaneMask.setMinimumSize(QtCore.QSize(420, 0))
        self.midplaneMask.setObjectName(_fromUtf8("midplaneMask"))
        self.verticalLayout_3.addWidget(self.midplaneMask)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.tabWidget.addTab(self.outputs, _fromUtf8(""))
        self.verticalLayout_4.addWidget(self.tabWidget)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.removeDuplicates = QtGui.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        self.removeDuplicates.setFont(font)
        self.removeDuplicates.setFocusPolicy(QtCore.Qt.TabFocus)
        self.removeDuplicates.setObjectName(_fromUtf8("removeDuplicates"))
        self.gridLayout.addWidget(self.removeDuplicates, 1, 2, 1, 1)
        self.addScans = QtGui.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        self.addScans.setFont(font)
        self.addScans.setObjectName(_fromUtf8("addScans"))
        self.gridLayout.addWidget(self.addScans, 1, 0, 1, 1)
        self.removeScans = QtGui.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        self.removeScans.setFont(font)
        self.removeScans.setObjectName(_fromUtf8("removeScans"))
        self.gridLayout.addWidget(self.removeScans, 1, 1, 1, 1)
        self.clearAll = QtGui.QPushButton(self.layoutWidget)
        self.clearAll.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        self.clearAll.setFont(font)
        self.clearAll.setFocusPolicy(QtCore.Qt.TabFocus)
        self.clearAll.setAutoFillBackground(False)
        self.clearAll.setStyleSheet(_fromUtf8(""))
        self.clearAll.setCheckable(False)
        self.clearAll.setAutoDefault(False)
        self.clearAll.setDefault(False)
        self.clearAll.setObjectName(_fromUtf8("clearAll"))
        self.gridLayout.addWidget(self.clearAll, 1, 3, 1, 1)
        self.scanList = QtGui.QListWidget(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        self.scanList.setFont(font)
        self.scanList.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scanList.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scanList.setAutoScroll(True)
        self.scanList.setDragEnabled(True)
        self.scanList.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.scanList.setObjectName(_fromUtf8("scanList"))
        self.gridLayout.addWidget(self.scanList, 0, 0, 1, 4)
        self.start = QtGui.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        self.start.setFont(font)
        self.start.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.start.setObjectName(_fromUtf8("start"))
        self.gridLayout.addWidget(self.start, 4, 0, 1, 4)
        self.verticalLayout_4.addLayout(self.gridLayout)
        self.log = QtGui.QListWidget(self.layoutWidget)
        self.log.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.log.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.log.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.log.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.log.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.log.setProperty("isWrapping", False)
        self.log.setViewMode(QtGui.QListView.ListMode)
        self.log.setObjectName(_fromUtf8("log"))
        self.verticalLayout_4.addWidget(self.log)
        self.allStop = QtGui.QPushButton(self.layoutWidget)
        self.allStop.setEnabled(False)
        self.allStop.setObjectName(_fromUtf8("allStop"))
        self.verticalLayout_4.addWidget(self.allStop)
        self.quitBtn = QtGui.QPushButton(self.layoutWidget)
        self.quitBtn.setObjectName(_fromUtf8("quitBtn"))
        self.verticalLayout_4.addWidget(self.quitBtn)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.tissues.setText(_translate("Dialog", "Tissue Types to Analyse", None))
        self.parenchyma.setText(_translate("Dialog", "Parenchyma", None))
        self.haematoma.setText(_translate("Dialog", "Haematoma", None))
        self.ventricles.setText(_translate("Dialog", "Ventricles", None))
        self.wholeBrain.setText(_translate("Dialog", "Whole brain", None))
        self.actions.setText(_translate("Dialog", "Actions", None))
        self.symmetry.setText(_translate("Dialog", "Symmetry Analysis", None))
        self.segmentation.setText(_translate("Dialog", "Tissue Segmentation Only", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.analysis), _translate("Dialog", "Analysis", None))
        self.label.setText(_translate("Dialog", "Numerical Outputs", None))
        self.totalSymmVolumes.setText(_translate("Dialog", "Tissue volumes on either side of midplane", None))
        self.totalVolumes.setText(_translate("Dialog", "Total volumes of selected tissue types", None))
        self.label_2.setText(_translate("Dialog", "Masks", None))
        self.tissueMasks.setText(_translate("Dialog", "Segmentations of all selected tissue types", None))
        self.lrTissueMasks.setText(_translate("Dialog", "Left and right sides of the midplane for selected tissue types", None))
        self.midplaneMask.setText(_translate("Dialog", "Midplane", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.outputs), _translate("Dialog", "Outputs", None))
        self.removeDuplicates.setText(_translate("Dialog", "Remove Duplicates", None))
        self.addScans.setText(_translate("Dialog", "Add Scans", None))
        self.removeScans.setText(_translate("Dialog", "Remove Scans", None))
        self.clearAll.setText(_translate("Dialog", "Clear All", None))
        self.start.setText(_translate("Dialog", "Start", None))
        self.allStop.setText(_translate("Dialog", "Stop all processes", None))
        self.quitBtn.setText(_translate("Dialog", "Quit", None))

